#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT_FOR_IMPORT = Path(__file__).resolve().parents[1]
if str(ROOT_FOR_IMPORT) not in sys.path:
    sys.path.insert(0, str(ROOT_FOR_IMPORT))

from selfcheck.pr_autonomy import dispatch_payload


def run(args: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(args, cwd=cwd, text=True, capture_output=True, timeout=60)


def markdown_summary(decision: dict) -> str:
    risk = decision.get("risk")
    if isinstance(risk, dict):
        risk_text = f"{risk.get('level')} ({', '.join(risk.get('reasons') or []) or 'no explicit risk reason'})"
    else:
        risk_text = str(risk)
    actions = ", ".join(decision.get("actions") or []) or "none"
    return f"""## AI PR Autonomy Decision

- State: `{decision.get('state')}`
- Terminal: `{decision.get('terminal')}`
- Risk: `{risk_text}`
- Reason: {decision.get('reason')}
- Planned actions: `{actions}`
- Dry run: `{decision.get('dry_run')}`

This report is generated by Agentic SelfCheck. Secrets are never included in this comment.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--policy", default="github-pr-autonomy-v-workspace")
    parser.add_argument("--payload-file", required=True)
    parser.add_argument("--repo", help="owner/repo for GitHub reporting")
    parser.add_argument("--pr", type=int, help="PR number for GitHub reporting")
    parser.add_argument("--apply", action="store_true", help="Apply GitHub comment/check reporting. Default is dry-run only.")
    parser.add_argument("--allow-merge", action="store_true", help="Allow actual merge if policy decision is READY_TO_MERGE. Requires --apply.")
    parser.add_argument("--report", default="reports/github-pr-autonomy/github-pr-autonomy-report.json")
    args = parser.parse_args()

    root = Path(args.root)
    payload = json.loads(Path(args.payload_file).read_text(encoding="utf-8"))
    decision = dispatch_payload(root, args.policy, payload)
    repo = args.repo or decision.get("repo")
    pr = args.pr or decision.get("pr")
    comment = markdown_summary(decision)
    applied: list[dict] = []

    if args.apply:
        if not repo or not pr:
            raise SystemExit("--repo and --pr are required for --apply")
        cp = run(["gh", "pr", "comment", str(pr), "--repo", str(repo), "--body", comment], cwd=root)
        applied.append({"action": "comment", "exit_code": cp.returncode, "stderr_tail": cp.stderr[-500:]})
        if cp.returncode != 0:
            raise SystemExit(cp.returncode)
        state = str(decision.get("state"))
        conclusion = "success" if state in {"PASS", "PASS_WITH_NOTES", "READY_FOR_HUMAN", "READY_TO_MERGE"} else "failure" if state == "BLOCKED" else "neutral"
        sha = str(decision.get("head_sha") or payload.get("head_sha") or "")
        if sha:
            cp = run([
                "gh", "api", f"repos/{repo}/statuses/{sha}",
                "-f", "state=success" if conclusion == "success" else "state=failure" if conclusion == "failure" else "state=pending",
                "-f", "context=AI Review / PR Autonomy",
                "-f", f"description={state}: {str(decision.get('reason'))[:120]}",
            ], cwd=root)
            applied.append({"action": "status", "exit_code": cp.returncode, "stderr_tail": cp.stderr[-500:]})
        if args.allow_merge and state == "READY_TO_MERGE" and "MERGE_PR_PLANNED_ONLY" in decision.get("actions", []):
            cp = run(["gh", "pr", "merge", str(pr), "--repo", str(repo), "--squash", "--delete-branch"], cwd=root)
            applied.append({"action": "merge", "exit_code": cp.returncode, "stderr_tail": cp.stderr[-500:]})
            if cp.returncode != 0:
                raise SystemExit(cp.returncode)

    report = {"status": "PASS", "decision": decision, "applied": applied, "apply": args.apply, "allow_merge": args.allow_merge}
    out = root / args.report
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
