#!/usr/bin/env python3
from __future__ import annotations
import argparse, shutil, re
from pathlib import Path

TEMPLATE_DIR = Path('templates/frontend/high-fidelity-prototype-gate')
DESIGN_QUALITY_TEMPLATE_DIR = Path('templates/frontend/design-quality-pack')
DESIGN_LANE_TEMPLATE_DIR = Path('templates/frontend/design-lane-generation')
PROTOTYPE_FREEZE_TEMPLATE_DIR = Path('templates/frontend/prototype-freeze')


def slugify(value: str) -> str:
    value=value.strip().lower()
    value=re.sub(r'[^a-z0-9]+','-',value)
    value=re.sub(r'-+','-',value).strip('-')
    if not value:
        raise SystemExit('empty workflow name after slugify')
    return value


def main() -> int:
    ap=argparse.ArgumentParser(description='Initialize a C/D risk frontend high-fidelity prototype workflow from generic templates.')
    ap.add_argument('--root', default='.', help='SelfCheck root')
    ap.add_argument('--name', required=True, help='Workflow/task name')
    ap.add_argument('--risk', choices=['C','D'], required=True)
    ap.add_argument('--project', default='', help='Target project/repo name')
    ap.add_argument('--title', default='', help='Human-readable title')
    ap.add_argument('--force', action='store_true')
    args=ap.parse_args()
    root=Path(args.root).resolve()
    tmpl=root/TEMPLATE_DIR
    dq_tmpl=root/DESIGN_QUALITY_TEMPLATE_DIR
    lane_tmpl=root/DESIGN_LANE_TEMPLATE_DIR
    freeze_tmpl=root/PROTOTYPE_FREEZE_TEMPLATE_DIR
    if not tmpl.exists():
        raise SystemExit(f'template dir missing: {tmpl}')
    if not dq_tmpl.exists():
        raise SystemExit(f'design quality template dir missing: {dq_tmpl}')
    if not lane_tmpl.exists():
        raise SystemExit(f'design lane template dir missing: {lane_tmpl}')
    if not freeze_tmpl.exists():
        raise SystemExit(f'prototype freeze template dir missing: {freeze_tmpl}')
    slug=slugify(args.name)
    wf=root/'.hermes/workflows'/slug
    if wf.exists() and not args.force:
        raise SystemExit(f'workflow exists: {wf}; use --force to overwrite generated template files')
    wf.mkdir(parents=True, exist_ok=True)
    for p in list(dq_tmpl.glob('*.md')) + list(lane_tmpl.glob('*.md')) + list(tmpl.glob('*.md')) + list(freeze_tmpl.glob('*.md')):
        target=wf/p.name
        if target.exists() and not args.force:
            continue
        text=p.read_text(encoding='utf-8')
        header=f"<!-- Generated by init_frontend_workflow.py; risk={args.risk}; project={args.project or 'unspecified'} -->\n\n"
        if args.title and p.name == 'DESIGN_BRIEF.md':
            text=text.replace('# Design Brief', f'# Design Brief: {args.title}', 1)
        target.write_text(header+text, encoding='utf-8')
    for d in ['reference-screenshots','design-lanes','prototype-artifacts','prototype-screenshots','production-screenshots','visual-evidence','browser-evidence','frozen-prototype']:
        (wf/d).mkdir(exist_ok=True)
        keep=wf/d/'.gitkeep'
        keep.write_text('placeholder; replace with real evidence files for gate pass\n', encoding='utf-8')

    # Pre-create explicit lane directories so a generated workflow has the right shape.
    try:
        from frontend_design_lane_gate import init_lanes
        init_lanes(root, wf, args.risk, args.force)
    except Exception as exc:
        raise SystemExit(f'failed to initialize design lanes: {exc}')
    readme=wf/'README.md'
    readme.write_text(f'''# Frontend Prototype Workflow: {args.title or slug}

- Risk: {args.risk}
- Project: {args.project or 'unspecified'}

## Required sequence

```text
Design quality pack -> design lanes -> critique -> scorecard -> acceptance -> prototype freeze -> parity plan -> implementation
```

## Validate

```bash
python3 scripts/frontend_design_quality_pack_gate.py --root . --workflow .hermes/workflows/{slug} --risk {args.risk} --format json
python3 scripts/frontend_design_lane_gate.py --root . --workflow .hermes/workflows/{slug} --risk {args.risk} --format json
python3 scripts/frontend_quality_gate.py --root . --workflow .hermes/workflows/{slug} --risk {args.risk} --format json
python3 scripts/frontend_prototype_freeze_gate.py --root . --workflow .hermes/workflows/{slug} --risk {args.risk} --format json
```

## Evidence dirs

- `prototype-artifacts/`: HTML/Figma exports/v0 output links captured as docs
- `prototype-screenshots/`: selected prototype screenshots
- `frozen-prototype/`: prototype-freeze gate output and implementation handoff artifacts
- `production-screenshots/`: implementation screenshots after build
- `visual-evidence/`: comparison notes/images
- `browser-evidence/`: Playwright/browser logs/screenshots
''', encoding='utf-8')
    print(wf)
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
